### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by trezum** [diego-oliv/SuperPasswordEncoder7#1]
The current code is a 1 to 1 mapping between letters and parts of a password.
I suggest introducing a desired password output length, hashing(SHA-256) the entered password and truncating the output of the hashfunction to the desired length.
If the user needs longer passwords you can hash the hash and concatinate.

If you need help ill make a PR with it :)

**Comment by sattvika** [comment]
That suggestion was amazing, in fact I was really weighing how to apply this to my code. If you can show me your idea, it would certainly be of great help.

**Comment by trezum** [comment]
I will create a PR within the next few days :)
